version: '3.9'

services:
    app:
        build:
            context: ./.docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: ip-guardian-image
        container_name: ip-guardian-app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - ip-guardian-net
        depends_on:
            - db

    db:
        image: mariadb:10.2
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-hdwjwj@1!jkkjdjw}'
            MYSQL_USER: '${DB_USERNAME:-root}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-hdwjwj@1!jkkjdjw}'
            MYSQL_DATABASE: '${DB_DATABASE:-ip_management_db}'
            MYSQL_ROOT_HOST: '%'
        volumes:
            - ip-guardian-db:/var/lib/mysql
        ports:
            - '${FORWARD_DB_PORT:-3313}:3306'
        networks:
            - ip-guardian-net
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    db_test:
        image: mariadb:10.2
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_TEST_PASSWORD:-hdwjwj@1!jkkjdjw}'
            MYSQL_USER: '${DB_TEST_USERNAME:-root}'
            MYSQL_PASSWORD: '${DB_TEST_PASSWORD:-hdwjwj@1!jkkjdjw}'
            MYSQL_DATABASE: '${DB_TEST_DATABASE:-ip_management_db}'
            MYSQL_ROOT_HOST: '%'
        volumes:
            - ip-guardian-db-test:/var/lib/mysql
        ports:
            - '${FORWARD_DB_TEST_PORT:-3313}:3306'
        networks:
            - ip-guardian-net
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_TEST_PASSWORD}'
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin:5.1.1
        depends_on:
            - db
        restart: unless-stopped
        ports:
            - '${FORWARD_PHPMYADMIN_PORT:-6610}:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-hdwjwj@1!jkkjdjw}'
            MYSQL_USER: '${DB_USERNAME:-root}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-hdwjwj@1!jkkjdjw}'
            UPLOAD_LIMIT: 500M
            MYSQL_ROOT_HOST: '%'
        networks:
            - ip-guardian-net


volumes:
    ip-guardian-db:
        driver: local
    ip-guardian-db-test:
        driver: local
      
networks:
  ip-guardian-net:
    driver: bridge
